#background transparancy 
background_opacity 0.5

#Font
font_size 12


#Cursor
cursor_trail 200
cursor_trail_start_threshold 2
cursor_trail_decay 0.1 0.4

cursor_shape block
cursor_blink true


# Theme
include current-theme.conf


#OS_Wiindow close warning
confirm_os_window_close 0

#Fish
shell /usr/bin/fish
